### ISSUE TITLE
[FIXED] Replace dead sample

### ISSUE THREAD

**Issue by sergeevabc** [dhiltonp/reddit-latex#1]
Dear David,
Sample output PDF is no longer available, link is dead.
Perhaps you could upload it right into this repository rather than move between temporary hosts?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by dhiltonp** [comment]
Hello.

I don't have a sample PDF handy; you could generate one, if you like?

**Comment by sergeevabc** [comment]
Do you mean you generated a sample, uploaded to a temporary host, then deleted a local copy? Oh.
Alas, I have no LaTeX here, but thought that possible beauty of your sample would motivate me to get it.

**Comment by dhiltonp** [comment]
I've updated the sample, modified the repo, and fixed an error.

**Comment by dhiltonp** [comment]
BTW, comments used to be inside of boxes, but they didn't cross page boundaries correctly :/

**Comment by sergeevabc** [comment]
@dhiltonp, thank you.
